
-- 
-- Editor server script for DB table inscrit
-- Automatically generated by http://editor.datatables.net/generator
-- 

CREATE TABLE `inscrit` (
	`id` int(10) NOT NULL auto_increment,
	`famille` varchar(255) default NULL,
	`prenom` varchar(255) default NULL,
	`adresse` varchar(255) default NULL,
	`cp` varchar(255) default NULL,
	`tel` varchar(255) default NULL,
	`email` varchar(255) default NULL,
	`ecole_prec` varchar(255) default NULL,
	`classe_desiree` varchar(255) default NULL,
	`fraterie` varchar(255) default NULL,
	`implication` varchar(255) default NULL,
	`points` varchar(255) default NULL,
	PRIMARY KEY  (`id`)
);

